# Generated by Django 6.1.1 on 2026-10-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=150)),
                ('current_year', models.CharField(max_length=30)),
                ('graduation_year', models.CharField(max_length=10)),
                ('cgpa', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.student')),
            ],
        ),
    ]
